model:
  name: sam2_hiera_large
  pretrained: true
  freeze_image_encoder: false
  freeze_prompt_encoder: false
  freeze_mask_decoder: false

data:
  train:
    root_dir: data/images
    ann_file: data/annotations/train.json
  val:
    root_dir: data/images
    ann_file: data/annotations/val.json
  num_workers: 8
  batch_size: 8
  image_size: 1024

training:
  epochs: 100
  lr: 1e-4
  weight_decay: 0.05
  warmup_epochs: 5
  optimizer: adamw
  scheduler: cosine
  grad_clip: 1.0
  mixed_precision: true
  checkpoint_dir: checkpoints
  log_dir: outputs/logs
  save_freq: 5

augmentation:
  random_resize: [0.5, 2.0]
  random_crop: true
  random_hflip: true
  color_jitter:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.1 